[package]
name = "file-server"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
axum =  {version = "0.4.3", features = ["multipart","headers"] }
tokio = { version = "1.0", features = ["full"]}
tower-http = { version = "0.2.0", features = ["fs", "trace"] }
headers = "0.3"
uuid = { version = "1.6.1", features = ["v4", "fast-rng", "macro-diagnostics"] }